<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>pyrochild.effects.gradientmapping</RootNamespace>
    <AssemblyName>Gradient Mapping</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>$(NoWarn);WFO1000</NoWarn>
    <MSBuildWarningsAsMessages>MSB3277</MSBuildWarningsAsMessages>

    <Product>Gradient Mapping</Product>
    <AssemblyTitle>Gradient Mapping</AssemblyTitle>
    <Description>Paint.NET Plugin</Description>
    <Company>Zach Walker, a.k.a. pyrochild</Company>
    <Copyright>Copyright © 2007-2026 Zach Walker</Copyright>

    <!-- Build/Revision come from the build date. -->
    <VersionPrefix>5.1</VersionPrefix>
    <AssemblyVersion>$(VersionPrefix).$([System.DateTime]::Now.ToString(yyMM)).$([System.DateTime]::Now.ToString(ddHH))</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PaintDotNet.Base">
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Base.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Core">
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Data">
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Data.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Effects">
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Effects.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Effects.Core">
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Effects.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Primitives">
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Primitives.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.ComponentModel">
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.ComponentModel.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.ObjectModel">
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.ObjectModel.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="PaintDotNet.Windows">
      <HintPath>C:\Program Files\Paint.NET\PaintDotNet.Windows.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="common\ColorWheel.resx">
      <DependentUpon>ColorWheel.cs</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="PresetDropdown\InputBox.resx">
      <DependentUpon>InputBox.cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="icon.png" />
  </ItemGroup>


  <PropertyGroup>
    <GradientMappingEffectsDir>$(USERPROFILE)\Documents\paint.net App Files\Effects\</GradientMappingEffectsDir>
  </PropertyGroup>

  <Target Name="GradientMappingCopyToEffectsFolder" AfterTargets="Build">
    <MakeDir Directories="$(GradientMappingEffectsDir)" Condition="!Exists('$(GradientMappingEffectsDir)')" ContinueOnError="WarnAndContinue" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(GradientMappingEffectsDir)" ContinueOnError="WarnAndContinue" />
  </Target>

</Project>
